### ISSUE TITLE
Support Laravel 8.x

### ISSUE THREAD

**Issue by litruk** [SPie/laravel-jwt#10]
Hi. Any plans to support Laravel 8.x?

**Comment by SPie** [comment]
Yes, I will take a look at that.

**Comment by SPie** [comment]
@litruk With version `v3.1.0` Laravel 8 will be supported.
But be aware of the `vlucas/phpdotenv` changes. I had to add support for version `^5.2` because in version `^8` of `illuminate/support` a new `RepositoryBuilder::createWithDefaultAdapters` method is used, but the package itself doesn't require `vlucas/phpdotenv`.
If you are using it with the whole `laravel/framework` it shouldn't be a problem.
